<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<!-- (We're currently using v3.99 with custom changes - once the changes are backported into the SDK we can revert to using the official version) -->
<!--<script type="text/javascript" src="https://api.addressy.com/js/address-3.99.js"></script>-->
<link rel="stylesheet" type="text/css" href="https://api.addressy.com/css/address-3.99.css" />

<script src="<?= $block->getViewFileUrl('Loqate_ApiIntegration::capture.js') ?>"></script>
<link href="<?= $block->getViewFileUrl('Loqate_ApiIntegration::capture.css') ?>" rel="stylesheet" type="text/css" />

<div id="loqate-urls"
     data-find-url="<?= $block->getUrl('loqate/capture/find'); ?>"
     data-retrieve-url="<?= $block->getUrl('loqate/capture/retrieve'); ?>">
</div>
