version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/loqate-magento:cached
    depends_on:
      - db
      - elasticsearch
      - redis
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    working_dir: /workspace/

  nginx:
    image: nginx:1.23-alpine
    ports:
      - "8080:80"
    volumes:
      - ../:/workspace/loqate-magento:cached
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  esdata:
  redisdata:
